create table yearly_fact_district
(
    Tahun                    bigint null,
    kode_prov                text   null,
    nama_prov                text   null,
    SUSPECT                  text   null,
    CLOSECONTACT             text   null,
    PROBABLE                 text   null,
    suspect_diisolasi        text   null,
    suspect_discarded        text   null,
    closecontact_dikarantina text   null,
    closecontact_discarded   text   null,
    probable_diisolasi       text   null,
    probable_discarded       text   null,
    CONFIRMATION             text   null,
    confirmation_sembuh      text   null,
    confirmation_meninggal   text   null,
    suspect_meninggal        text   null,
    closecontact_meninggal   text   null,
    probable_meninggal       text   null
);

INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3201', 'Kabupaten Bogor', '6567', '0', '43312', '2269', '6125', '0', '0', '2449', '8499', '4028', '3955', '16', '702', '0', '32364');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3202', 'Kabupaten Sukabumi', '6168', '3473', '6558', '509', '6022', '1297', '3142', '274', '625', '1979', '1839', '19', '45', '0', '5659');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3203', 'Kabupaten Cianjur', '1950', '1594', '496', '451', '1662', '845', '916', '31', '207', '197', '195', '2', '110', '0', '258');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3204', 'Kabupaten Bandung', '3429', '4182', '4523', '671', '2850', '1392', '3880', '45', '0', '3978', '3233', '30', '158', '0', '4478');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3205', 'Kabupaten Garut', '4452', '16929', '0', '3097', '4268', '6410', '15891', '0', '0', '2672', '2385', '39', '9', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3206', 'Kabupaten Tasikmalaya', '1831', '1912', '1236', '104', '1808', '681', '1827', '80', '82', '402', '399', '3', '21', '0', '1074');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3207', 'Kabupaten Ciamis', '2145', '16766', '447', '2124', '2117', '3818', '15643', '0', '447', '590', '513', '14', '21', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3208', 'Kabupaten Kuningan', '2792', '2050', '2701', '2051', '2664', '1236', '1447', '157', '1861', '1607', '1103', '13', '35', '0', '683');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3209', 'Kabupaten Cirebon', '476', '5945', '916', '48', '465', '904', '5573', '0', '0', '2029', '1539', '71', '102', '0', '917');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3210', 'Kabupaten Majalengka', '1041', '4729', '3360', '202', '937', '2305', '4102', '0', '0', '1254', '1031', '30', '23', '0', '3360');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3211', 'Kabupaten Sumedang', '1348', '2569', '1183', '1091', '1325', '1097', '2288', '0', '0', '1036', '778', '20', '22', '0', '1183');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3212', 'Kabupaten Indramayu', '1979', '4584', '11348', '396', '1899', '1330', '3901', '0', '0', '785', '768', '12', '80', '0', '11348');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3213', 'Kabupaten Subang', '5803', '455', '2670', '12', '5803', '50', '455', '0', '2670', '500', '460', '13', '62', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3214', 'Kabupaten Purwakarta', '1347', '2342', '983', '462', '1114', '1394', '1769', '15', '110', '1657', '1477', '37', '95', '0', '858');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3215', 'Kabupaten Karawang', '7279', '8192', '8522', '469', '7162', '2339', '6949', '0', '0', '5793', '4255', '136', '99', '0', '8522');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3216', 'Kabupaten Bekasi', '11116', '12333', '20618', '4978', '10892', '2935', '11966', '1012', '12730', '8391', '7283', '61', '353', '0', '6876');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3217', 'Kabupaten Bandung Barat', '873', '1757', '3878', '61', '818', '773', '1502', '26', '641', '1375', '1094', '15', '80', '0', '3211');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3218', 'Kabupaten Pangandaran', '708', '1570', '185', '60', '694', '880', '1383', '43', '0', '141', '140', '1', '18', '0', '142');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3271', 'Kota Bogor', '3773', '4759', '9592', '788', '3357', '1510', '3864', '184', '1207', '3781', '3661', '62', '203', '0', '8201');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3272', 'Kota Sukabumi', '1519', '6559', '1062', '701', '1145', '2555', '5205', '0', '42', '880', '859', '19', '3', '0', '1020');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3273', 'Kota Bandung', '12258', '16741', '25205', '9756', '9988', '5552', '16064', '0', '21900', '6361', '5704', '86', '224', '0', '3305');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3274', 'Kota Cirebon', '437', '3832', '250', '42', '432', '1826', '2716', '0', '125', '741', '720', '15', '30', '0', '125');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3275', 'Kota Bekasi', '11372', '17009', '52678', '412', '11301', '1672', '16858', '6346', '36386', '13924', '11572', '140', '310', '0', '9946');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3276', 'Kota Depok', '12351', '23244', '4736', '1793', '11764', '5574', '20646', '3700', '0', '12270', '9900', '228', '245', '0', '1036');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3277', 'Kota Cimahi', '1980', '12169', '878', '951', '1801', '5414', '11893', '0', '0', '2758', '2552', '41', '30', '0', '878');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3278', 'Kota Tasikmalaya', '1484', '1442', '12040', '1395', '1453', '311', '1239', '677', '10112', '1982', '976', '28', '22', '0', '1250');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2020, '3279', 'Kota Banjar', '743', '1934', '0', '570', '696', '1033', '1771', '0', '0', '316', '254', '12', '23', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3201', 'Kabupaten Bogor', '1358', '0', '193733', '1221', '1347', '0', '0', '6205', '43070', '44099', '43939', '190', '0', '0', '144458');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3202', 'Kabupaten Sukabumi', '5508', '14276', '196654', '631', '5123', '2397', '13065', '5860', '125958', '9391', '9197', '308', '0', '0', '64836');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3203', 'Kabupaten Cianjur', '1349', '2308', '33405', '239', '1445', '928', '2486', '2854', '18833', '10705', '10505', '199', '0', '0', '11664');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3204', 'Kabupaten Bandung', '2381', '74716', '11315', '370', '2905', '568', '73762', '0', '0', '30344', '30456', '580', '0', '0', '11315');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3205', 'Kabupaten Garut', '6932', '5626', '612', '1630', '6899', '1799', '6190', '0', '0', '24139', '23249', '1133', '0', '0', '612');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3206', 'Kabupaten Tasikmalaya', '374', '1830', '6055', '198', '336', '656', '1763', '102', '2381', '6661', '6387', '270', '0', '0', '3572');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3207', 'Kabupaten Ciamis', '86', '34642', '1095', '53', '59', '1592', '35667', '0', '1095', '14591', '14357', '297', '0', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3208', 'Kabupaten Kuningan', '844', '21620', '26714', '293', '928', '3907', '20939', '3857', '18927', '11924', '12181', '233', '0', '0', '3930');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3209', 'Kabupaten Cirebon', '53', '15501', '11176', '0', '64', '10762', '9946', '0', '0', '23091', '22653', '820', '0', '0', '11176');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3210', 'Kabupaten Majalengka', '1211', '10579', '32897', '412', '1211', '4608', '8412', '0', '0', '9841', '9835', '192', '0', '0', '32897');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3211', 'Kabupaten Sumedang', '941', '2322', '32733', '348', '922', '1005', '2332', '0', '0', '8043', '8155', '120', '0', '0', '32733');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3212', 'Kabupaten Indramayu', '7724', '24413', '47336', '3134', '7119', '9956', '24178', '0', '3427', '15076', '14392', '687', '0', '0', '43909');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3213', 'Kabupaten Subang', '619', '518', '11958', '171', '519', '0', '518', '0', '11958', '9198', '8961', '261', '0', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3214', 'Kabupaten Purwakarta', '3572', '4737', '11844', '863', '3468', '949', '4432', '0', '365', '10770', '10372', '541', '0', '0', '11479');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3215', 'Kabupaten Karawang', '1503', '35019', '30658', '534', '1569', '9290', '34483', '0', '0', '37551', '37219', '1729', '0', '0', '30658');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3216', 'Kabupaten Bekasi', '15126', '25329', '388066', '2747', '14908', '4212', '24587', '26865', '323072', '43073', '43620', '482', '0', '0', '38129');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3217', 'Kabupaten Bandung Barat', '413', '1519', '18968', '262', '417', '1130', '1377', '0', '1825', '17877', '17887', '251', '0', '0', '17143');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3218', 'Kabupaten Pangandaran', '245', '463', '4676', '49', '259', '159', '650', '330', '1404', '5140', '4995', '145', '0', '0', '2942');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3271', 'Kota Bogor', '2442', '9085', '38398', '976', '2674', '3091', '9425', '0', '4015', '33532', '33081', '465', '0', '0', '34383');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3272', 'Kota Sukabumi', '9231', '9466', '10424', '339', '9438', '3271', '10543', '0', '883', '8382', '8118', '264', '0', '0', '9541');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3273', 'Kota Bandung', '14730', '16162', '63510', '6371', '13322', '3602', '16512', '0', '54750', '39446', '39646', '314', '0', '0', '8760');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3274', 'Kota Cirebon', '2256', '6552', '730', '111', '2204', '1248', '6953', '0', '365', '12098', '11567', '513', '0', '0', '365');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3275', 'Kota Bekasi', '11476', '49834', '591695', '289', '11537', '765', '49863', '22602', '483021', '80893', '82211', '876', '0', '0', '86072');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3276', 'Kota Depok', '13318', '51203', '11680', '703', '13461', '5384', '49385', '9125', '0', '93618', '93799', '1944', '0', '0', '2555');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3277', 'Kota Cimahi', '2507', '2915', '8577', '1189', '2146', '983', '3009', '111', '0', '9256', '9078', '137', '0', '0', '8467');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3278', 'Kota Tasikmalaya', '1175', '11370', '46999', '3', '1184', '131', '11239', '1916', '32487', '11925', '12385', '513', '0', '0', '12596');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2021, '3279', 'Kota Banjar', '2291', '1352', '15162', '836', '2292', '296', '1450', '305', '4750', '4586', '4516', '120', '0', '0', '10107');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3201', 'Kabupaten Bogor', '0', '0', '175357', '0', '0', '0', '0', '5593', '38822', '54723', '53484', '0', '0', '0', '130942');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3202', 'Kabupaten Sukabumi', '0', '0', '276360', '0', '0', '0', '0', '1316', '193452', '5255', '5128', '31', '0', '0', '81592');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3203', 'Kabupaten Cianjur', '0', '0', '42770', '0', '0', '0', '0', '2303', '26978', '4929', '4838', '26', '0', '0', '13489');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3204', 'Kabupaten Bandung', '0', '0', '10199', '0', '0', '0', '0', '0', '0', '23644', '22882', '26', '0', '0', '10199');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3205', 'Kabupaten Garut', '0', '0', '1316', '0', '0', '0', '0', '0', '0', '8018', '7738', '128', '0', '0', '1316');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3206', 'Kabupaten Tasikmalaya', '0', '0', '5922', '0', '0', '0', '0', '0', '2632', '3574', '3452', '48', '0', '0', '3290');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3207', 'Kabupaten Ciamis', '0', '0', '987', '0', '0', '0', '0', '0', '987', '1580', '1522', '17', '0', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3208', 'Kabupaten Kuningan', '0', '0', '34216', '0', '0', '0', '0', '5264', '25004', '3598', '3498', '44', '0', '0', '3948');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3209', 'Kabupaten Cirebon', '0', '0', '13489', '0', '0', '0', '0', '0', '0', '7500', '7334', '87', '0', '0', '13489');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3210', 'Kabupaten Majalengka', '0', '0', '36190', '0', '0', '0', '0', '0', '0', '3070', '2979', '46', '0', '0', '36190');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3211', 'Kabupaten Sumedang', '0', '0', '49350', '0', '0', '0', '0', '0', '0', '4834', '4642', '46', '0', '0', '49350');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3212', 'Kabupaten Indramayu', '0', '0', '59549', '0', '0', '0', '0', '0', '7567', '6300', '6052', '67', '0', '0', '51982');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3213', 'Kabupaten Subang', '0', '0', '12502', '0', '0', '0', '0', '0', '12502', '5102', '4977', '25', '0', '0', '0');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3214', 'Kabupaten Purwakarta', '0', '0', '14147', '0', '0', '0', '0', '0', '329', '5064', '4953', '37', '0', '0', '13818');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3215', 'Kabupaten Karawang', '0', '0', '28623', '0', '0', '0', '0', '0', '0', '13849', '13267', '185', '0', '0', '28623');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3216', 'Kabupaten Bekasi', '0', '0', '486920', '0', '0', '0', '0', '36848', '403683', '40117', '39156', '28', '0', '0', '46389');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3217', 'Kabupaten Bandung Barat', '0', '0', '18424', '0', '0', '0', '0', '0', '1645', '10693', '10290', '42', '0', '0', '16779');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3218', 'Kabupaten Pangandaran', '0', '0', '5922', '0', '0', '0', '0', '0', '1974', '799', '777', '11', '0', '0', '3948');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3271', 'Kota Bogor', '0', '0', '35532', '0', '0', '0', '0', '0', '3619', '29752', '28608', '30', '0', '0', '31913');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3272', 'Kota Sukabumi', '0', '0', '10528', '0', '0', '0', '0', '0', '987', '3464', '3390', '8', '0', '0', '9541');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3273', 'Kota Bandung', '0', '0', '57246', '0', '0', '0', '0', '0', '49350', '63688', '60643', '54', '0', '0', '7896');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3274', 'Kota Cirebon', '0', '0', '658', '0', '0', '0', '0', '0', '329', '4540', '4357', '44', '0', '0', '329');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3275', 'Kota Bekasi', '0', '0', '637602', '0', '0', '0', '0', '29939', '507976', '102969', '100952', '50', '0', '0', '99687');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3276', 'Kota Depok', '0', '0', '10528', '0', '0', '0', '0', '8225', '0', '79943', '75751', '100', '0', '0', '2303');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3277', 'Kota Cimahi', '0', '0', '11515', '0', '0', '0', '0', '0', '0', '11451', '11230', '22', '0', '0', '11515');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3278', 'Kota Tasikmalaya', '0', '0', '50995', '0', '0', '0', '0', '1316', '32571', '5437', '5065', '55', '0', '0', '17108');
INSERT INTO data_enginner_master.yearly_fact_district (Tahun, kode_prov, nama_prov, SUSPECT, CLOSECONTACT, PROBABLE, suspect_diisolasi, suspect_discarded, closecontact_dikarantina, closecontact_discarded, probable_diisolasi, probable_discarded, CONFIRMATION, confirmation_sembuh, confirmation_meninggal, suspect_meninggal, closecontact_meninggal, probable_meninggal) VALUES (2022, '3279', 'Kota Banjar', '0', '0', '22043', '0', '0', '0', '0', '0', '5264', '1297', '1257', '15', '0', '0', '16779');
